# Docs: https://github.com/Azure/webapps-deploy
name: Deploy Python Flask App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Checkout full repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Create virtual environment and install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Deploy all repo files to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'multi-agent-blog-writer'  # Your App Service name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: '.'  # Deploy full repo
