name: Deploy Python Flask App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'crewai-blog-writer-agents'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: '.'

